source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins
# gem 'jemoji', group: :jekyll_plugins
# gem 'jekyll-admin', group: :jekyll_plugins

gem "jekyll-image-size", "~> 1.2"

gem "jemoji", "~> 0.12.0"
